/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    featureGrid: FeatureGridBlock;
    featureShowcase: FeatureShowcaseBlock;
    steps: StepsBlock;
    codeBlock: CodeBlockBlock;
    productDemo: ProductDemoBlock;
    statsBand: StatsBandBlock;
    comparisonTable: ComparisonTableBlock;
    faq: FaqBlock;
    cta: CtaBlock;
    content: ContentBlock;
    mediaBlock: MediaBlock;
  };
  collections: {
    pages: Page;
    media: Media;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  header?: {
    eyebrow?: string | null;
    heading?: string | null;
    intro?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    align?: ('start' | 'center') | null;
  };
  columns?: ('2' | '3' | '4') | null;
  items: {
    icon?:
      | (
          | 'Activity'
          | 'Radio'
          | 'Bug'
          | 'Camera'
          | 'Video'
          | 'Route'
          | 'Repeat2'
          | 'ShieldCheck'
          | 'Database'
          | 'Cloud'
          | 'Users'
          | 'KeyRound'
          | 'GitBranch'
          | 'Layers'
          | 'Timer'
          | 'Search'
        )
      | null;
    title: string;
    description: string;
    link?: {
      type?: ('internal' | 'custom') | null;
      newTab?: boolean | null;
      reference?: (number | null) | Page;
      /**
       * An absolute URL, a mailto: address or a path such as /features.
       */
      url?: string | null;
      label?: string | null;
    };
    id?: string | null;
  }[];
  settings?: {
    background?: ('default' | 'sunken' | 'accent') | null;
    spacing?: ('normal' | 'compact') | null;
    /**
     * Optional #id for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero?: {
    variant?: ('none' | 'centered' | 'split') | null;
    eyebrow?: string | null;
    heading?: string | null;
    lead?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('internal' | 'custom') | null;
            newTab?: boolean | null;
            reference?: (number | null) | Page;
            /**
             * An absolute URL, a mailto: address or a path such as /features.
             */
            url?: string | null;
            label: string;
            appearance?: ('primary' | 'secondary' | 'ghost' | 'link') | null;
          };
          id?: string | null;
        }[]
      | null;
    demo?:
      | (
          | 'active-runs'
          | 'runs-table'
          | 'run-summary'
          | 'run-errors'
          | 'result-attempts'
          | 'dashboard-metrics'
          | 'pass-fail-chart'
          | 'flaky-tests'
          | 'explorer-table'
        )
      | null;
    media?: {
      light?: (number | null) | Media;
      /**
       * Optional. Falls back to the light image.
       */
      dark?: (number | null) | Media;
    };
    snippet?: {
      language?: ('ts' | 'js' | 'bash' | 'yaml' | 'json' | 'env') | null;
      code?: string | null;
    };
  };
  layout: (
    | FeatureGridBlock
    | FeatureShowcaseBlock
    | StepsBlock
    | CodeBlockBlock
    | ProductDemoBlock
    | StatsBandBlock
    | ComparisonTableBlock
    | FaqBlock
    | CtaBlock
    | ContentBlock
    | MediaBlock
  )[];
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * The path this page lives at. "home" is the site root.
   */
  slug: string;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  theme?: ('light' | 'dark' | 'neutral') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    showcase?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureShowcaseBlock".
 */
export interface FeatureShowcaseBlock {
  header?: {
    eyebrow?: string | null;
    heading?: string | null;
    intro?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    align?: ('start' | 'center') | null;
  };
  bullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  mediaSide?: ('left' | 'right') | null;
  visual?: {
    kind?: ('media' | 'demo') | null;
    media?: {
      light?: (number | null) | Media;
      /**
       * Optional. Falls back to the light image.
       */
      dark?: (number | null) | Media;
    };
    demo?:
      | (
          | 'active-runs'
          | 'runs-table'
          | 'run-summary'
          | 'run-errors'
          | 'result-attempts'
          | 'dashboard-metrics'
          | 'pass-fail-chart'
          | 'flaky-tests'
          | 'explorer-table'
        )
      | null;
    frame?: ('browser' | 'plain') | null;
    caption?: string | null;
  };
  link?: {
    type?: ('internal' | 'custom') | null;
    newTab?: boolean | null;
    reference?: (number | null) | Page;
    /**
     * An absolute URL, a mailto: address or a path such as /features.
     */
    url?: string | null;
    label?: string | null;
  };
  settings?: {
    background?: ('default' | 'sunken' | 'accent') | null;
    spacing?: ('normal' | 'compact') | null;
    /**
     * Optional #id for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock".
 */
export interface StepsBlock {
  header?: {
    eyebrow?: string | null;
    heading?: string | null;
    intro?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    align?: ('start' | 'center') | null;
  };
  steps: {
    title: string;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    code?: {
      language?: ('ts' | 'js' | 'bash' | 'yaml' | 'json' | 'env') | null;
      code?: string | null;
    };
    media?: {
      light?: (number | null) | Media;
      /**
       * Optional. Falls back to the light image.
       */
      dark?: (number | null) | Media;
    };
    id?: string | null;
  }[];
  link?: {
    type?: ('internal' | 'custom') | null;
    newTab?: boolean | null;
    reference?: (number | null) | Page;
    /**
     * An absolute URL, a mailto: address or a path such as /features.
     */
    url?: string | null;
    label?: string | null;
  };
  settings?: {
    background?: ('default' | 'sunken' | 'accent') | null;
    spacing?: ('normal' | 'compact') | null;
    /**
     * Optional #id for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'steps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlockBlock".
 */
export interface CodeBlockBlock {
  header?: {
    eyebrow?: string | null;
    heading?: string | null;
    intro?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    align?: ('start' | 'center') | null;
  };
  tabs: {
    label: string;
    language?: ('ts' | 'js' | 'bash' | 'yaml' | 'json' | 'env') | null;
    code: string;
    id?: string | null;
  }[];
  caption?: string | null;
  settings?: {
    background?: ('default' | 'sunken' | 'accent') | null;
    spacing?: ('normal' | 'compact') | null;
    /**
     * Optional #id for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'codeBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductDemoBlock".
 */
export interface ProductDemoBlock {
  header?: {
    eyebrow?: string | null;
    heading?: string | null;
    intro?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    align?: ('start' | 'center') | null;
  };
  demo:
    | 'active-runs'
    | 'runs-table'
    | 'run-summary'
    | 'run-errors'
    | 'result-attempts'
    | 'dashboard-metrics'
    | 'pass-fail-chart'
    | 'flaky-tests'
    | 'explorer-table';
  frame?: ('browser' | 'plain') | null;
  caption?: string | null;
  settings?: {
    background?: ('default' | 'sunken' | 'accent') | null;
    spacing?: ('normal' | 'compact') | null;
    /**
     * Optional #id for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'productDemo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBandBlock".
 */
export interface StatsBandBlock {
  header?: {
    eyebrow?: string | null;
    heading?: string | null;
    intro?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    align?: ('start' | 'center') | null;
  };
  items: {
    value: string;
    label: string;
    hint?: string | null;
    id?: string | null;
  }[];
  settings?: {
    background?: ('default' | 'sunken' | 'accent') | null;
    spacing?: ('normal' | 'compact') | null;
    /**
     * Optional #id for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonTableBlock".
 */
export interface ComparisonTableBlock {
  header?: {
    eyebrow?: string | null;
    heading?: string | null;
    intro?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    align?: ('start' | 'center') | null;
  };
  columns: {
    label: string;
    highlight?: boolean | null;
    id?: string | null;
  }[];
  rows: {
    capability: string;
    /**
     * One cell per column, in the same order.
     */
    cells: {
      state: 'yes' | 'partial' | 'no' | 'planned';
      note?: string | null;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  footnote?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  settings?: {
    background?: ('default' | 'sunken' | 'accent') | null;
    spacing?: ('normal' | 'compact') | null;
    /**
     * Optional #id for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'comparisonTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  header?: {
    eyebrow?: string | null;
    heading?: string | null;
    intro?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    align?: ('start' | 'center') | null;
  };
  items: {
    question: string;
    answer: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  settings?: {
    background?: ('default' | 'sunken' | 'accent') | null;
    spacing?: ('normal' | 'compact') | null;
    /**
     * Optional #id for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  heading: string;
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('internal' | 'custom') | null;
          newTab?: boolean | null;
          reference?: (number | null) | Page;
          /**
           * An absolute URL, a mailto: address or a path such as /features.
           */
          url?: string | null;
          label: string;
          appearance?: ('primary' | 'secondary' | 'ghost' | 'link') | null;
        };
        id?: string | null;
      }[]
    | null;
  tone?: ('default' | 'accent') | null;
  settings?: {
    background?: ('default' | 'sunken' | 'accent') | null;
    spacing?: ('normal' | 'compact') | null;
    /**
     * Optional #id for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns: {
    width?: ('full' | 'half' | 'third') | null;
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    id?: string | null;
  }[];
  settings?: {
    background?: ('default' | 'sunken' | 'accent') | null;
    spacing?: ('normal' | 'compact') | null;
    /**
     * Optional #id for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: {
    light: number | Media;
    /**
     * Optional. Falls back to the light image.
     */
    dark?: (number | null) | Media;
  };
  frame?: ('browser' | 'plain' | 'none') | null;
  size?: ('content' | 'wide' | 'full') | null;
  caption?: string | null;
  settings?: {
    background?: ('default' | 'sunken' | 'accent') | null;
    spacing?: ('normal' | 'compact') | null;
    /**
     * Optional #id for in-page links.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        variant?: T;
        eyebrow?: T;
        heading?: T;
        lead?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        demo?: T;
        media?:
          | T
          | {
              light?: T;
              dark?: T;
            };
        snippet?:
          | T
          | {
              language?: T;
              code?: T;
            };
      };
  layout?: T | {};
  generateSlug?: T;
  slug?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  theme?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        showcase?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Optional. Falls back to the site name set in Site settings.
   */
  logo?: (number | null) | Media;
  navItems?:
    | {
        link: {
          type?: ('internal' | 'custom') | null;
          newTab?: boolean | null;
          reference?: (number | null) | Page;
          /**
           * An absolute URL, a mailto: address or a path such as /features.
           */
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  ctas?:
    | {
        link: {
          type?: ('internal' | 'custom') | null;
          newTab?: boolean | null;
          reference?: (number | null) | Page;
          /**
           * An absolute URL, a mailto: address or a path such as /features.
           */
          url?: string | null;
          label: string;
          appearance?: ('primary' | 'secondary' | 'ghost' | 'link') | null;
        };
        id?: string | null;
      }[]
    | null;
  showGithub?: boolean | null;
  showThemeToggle?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        title: string;
        links?:
          | {
              link: {
                type?: ('internal' | 'custom') | null;
                newTab?: boolean | null;
                reference?: (number | null) | Page;
                /**
                 * An absolute URL, a mailto: address or a path such as /features.
                 */
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legal?:
    | {
        link: {
          type?: ('internal' | 'custom') | null;
          newTab?: boolean | null;
          reference?: (number | null) | Page;
          /**
           * An absolute URL, a mailto: address or a path such as /features.
           */
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Use {year} for the current year.
   */
  copyright?: string | null;
  social?:
    | {
        platform: 'github' | 'x' | 'linkedin' | 'bluesky';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  /**
   * Default meta description.
   */
  description?: string | null;
  githubUrl?: string | null;
  /**
   * Placeholder until the docs site exists.
   */
  docsUrl?: string | null;
  defaultOgImage?: (number | null) | Media;
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    link?: {
      type?: ('internal' | 'custom') | null;
      newTab?: boolean | null;
      reference?: (number | null) | Page;
      /**
       * An absolute URL, a mailto: address or a path such as /features.
       */
      url?: string | null;
      label?: string | null;
    };
  };
  /**
   * Modelled now, wired up once the privacy notice is final.
   */
  analytics?: {
    provider?: ('none' | 'plausible' | 'umami') | null;
    domain?: string | null;
    scriptUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  ctas?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  showGithub?: T;
  showThemeToggle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  legal?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  copyright?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  githubUrl?: T;
  docsUrl?: T;
  defaultOgImage?: T;
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  analytics?:
    | T
    | {
        provider?: T;
        domain?: T;
        scriptUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}